<?php

namespace ContainerEosU4aJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDisque2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.bjjaRAq.App\Entity\Disque' shared service.
     *
     * @return \App\Entity\Disque
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.bjjaRAq": it needs an instance of "App\\Entity\\Disque" but this type has been excluded in "config/services.yaml".');
    }
}
