<?php

namespace ContainerEosU4aJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDisqueTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\DisqueType' shared autowired service.
     *
     * @return \App\Form\DisqueType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/DisqueType.php';

        return $container->privates['App\\Form\\DisqueType'] = new \App\Form\DisqueType();
    }
}
